// HomeScreenStyles.js
import { StyleSheet } from 'react-native';

const homeScreenStyles = StyleSheet.create({
    container: { flex: 1 },
    topSection: { paddingHorizontal: 10 },
    navButtons: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      paddingVertical: 30,
      backgroundColor: '#FFF',
      borderRadius: 25,
      margin: 5,
    },
    locationContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 2,
      borderRadius: 10,
      marginBottom: 5,
    },
    locationHomeIcon: { width: 12, height: 12, marginBottom: 1 },
    locationNextIcon: { width: 16, height: 16 },
    locationText: { fontWeight: 'bold', marginLeft: 5, fontSize: 12 },
    locationAddress: { flex: 1, marginLeft: 5, color: '#000', fontSize: 12 },
    brandMallContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 10,
      borderRadius: 10,
    },
    brandToggleContainer: {
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      width: '20%',
    },
    brandMallText: { fontWeight: 'bold', fontSize: 12 },
    toggleSwitch: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
      width: 60,
      height: 25,
      marginTop: 5,
      backgroundColor: '#e1e1e6',
      borderRadius: 12.5,
    },
    toggleCircle: {
      width: 22,
      height: 22,
      backgroundColor: 'white',
      borderRadius: 10,
      marginRight: 5,
    },
    offText: { fontWeight: 'bold', fontSize: 14, color: '#000' },
    rowContainer: {
      backgroundColor: '#FFF',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 0,
      width: '80%',
      marginLeft: 10,
      borderWidth: 1,
      borderColor: '#beb4fa',
      borderRadius: 10,
      paddingRight: 10,
    },
    searchInput: {
      paddingLeft: 10,
      paddingVertical: 10,
      height: 50,
      flex: 1,
      color: '#000',
    },
    icon: { width: 24, height: 24, marginLeft: 10 },
    bannerContainer: {
      borderRadius: 10,
      overflow: 'hidden',
      marginHorizontal: 15,
      marginBottom: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    iconWrapper: { alignItems: 'center', justifyContent: 'center', margin: 5 },
    downIcon: { width: 16, height: 16 },
    bannerImage: {
      width: '100%',
      height: 160,
      backgroundColor: '#ddd',
      borderRadius: 20,
      paddingHorizontal: 20,
    },
    popularCategoriesContainer: { marginVertical: 10 },
    categoriesContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      paddingHorizontal: 10,
    },
    categoryColumn: {
      flexDirection: 'column',
      justifyContent: 'space-between',
    },
    category: {
      marginBottom: 10,
      alignItems: 'center',
      width: 100,
    },
    categoryImage: {
      width: 50,
      height: 50,
      backgroundColor: '#ccc',
      borderRadius: 40,
      marginBottom: 5,
    },
    categoryText: { fontSize: 12 },
    popularHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: 15,
      paddingVertical: 10,
      alignItems: 'center',
    },
    popularHeaderText: {
      fontWeight: 'bold',
      fontSize: 16,
      color: '#000',
    },
    arrowButton: {
      width: 16,
      height: 16,
      borderWidth: 1,
      borderRadius: 8,
      borderColor: '#000',
      justifyContent: 'center',
      alignItems: 'center',
    },
    popularProductsContainer: { marginBottom: 20, flexDirection: 'row'},
    productCard: {
      marginHorizontal: 10,
      width: 120,
      height: 160,
      backgroundColor: '#f0f0f0',
      borderRadius: 10,
    },
    productImage: {
      width: '100%',
      height: '100%',
      backgroundColor: '#ccc',
      borderRadius: 10,
    },
    itemContainer: {
      padding: 15,
      borderBottomWidth: 1,
      borderColor: '#e1e1e1',
    },
    itemText: {
      fontSize: 18,
      fontWeight: '500',
    },
  });
  

export default homeScreenStyles;
